name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: directory change 
        run: |
          Install: yarn install
          start: yarn start
            sh ./scripts/script.sh
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          wait-on: "http://localhost:3000"
          
          
