name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          
      - name: Install Project Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn start ; sleep 60 & cd /Users/joeladelubi/stream-chat-react/examples/typescript-app ; yarn start
        # wait-on: "http://localhost:3000"

      - name: upload failure screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: upload failure videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

          
          
