name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: directory change , install packages and start app
        run: |
          yarn install ; start: yarn start &
            sh ./scripts/script.sh
          wait-on: "http://localhost:3000"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          # wait-on: "http://localhost:3000"
          
          
