name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

      - name: Install Project Dependencies and Build
        run: yarn install

      - name: Install Example app
        working-directory: ./examples/typescript-app
        run: yarn install

      - name: Run Tests
        working-directory: ./examples/typescript-app
        run: yarn test:e2e:ci
        env:
          CYPRESS_BASE_URL: http://localhost:3000

      - name: upload failure screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: upload failure videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
