name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: directory change , install packages and start app
        uses: actions/setup-node@v2
        with:
          build: yarn install
          start: yarn start
            sh ./scripts/script.sh
          wait-on: "http://localhost:3000"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          # wait-on: "http://localhost:3000"
          
          
