name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          build: npm run build
          start: npm start
          install: npm install -g concurrently
          env:
            path = ../stream-chat-react/examples/typescript-app/
          run:
            cd path & exec yarn;yarn start
          wait-on: "http://localhost:3000"
          
          
